apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
      - image: ghcr.io/2022-4400-exp/4423-go-helloworld-2:2236885982e63b20d15b68d3ddc800ba7b88a876@sha256:9ed770a54ae00574333a0ee197bda203838e7c42ebd165422d039007feaaea22
        name: go-helloworld-2